micronaut:
  application:
    name: body-db

bodydb:
  api-key: ${BODYDB_API_KEY:}

datasources:
  default:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:bodydb}
    username: ${POSTGRES_USER:bodydb}
    password: ${POSTGRES_PASSWORD:bodydb}
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    schema-generate: none

flyway:
  datasources:
    default:
      enabled: true
      locations: classpath:db/migration
